config/routes.rb
require 'sidekiq/web'

Rails.application.routes.draw do
  root to: 'authentication#spotify'
  mount Sidekiq::Web => '/sidekiq'
  
  devise_for :users
  devise_scope :user do  
    get '/users/sign_out' => 'devise/sessions#destroy'     
  end

  resources :playlists
  resources :tracks

  get '/auth/spotify/callback', to: 'authentication#spotify'
end
 

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/playlist.rb
class Playlist < ApplicationRecord
  belongs_to :user
  has_many :tracks, dependent: :destroy

  serialize :owner, Hash
end

app/models/track.rb
class Track < ApplicationRecord
  belongs_to :playlist

  enum status: {on_queue:0 , played: 1}
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  
  serialize :user_hash, Hash
  has_many :playlists
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
    def after_sign_in_path_for(resource)
        playlists_path
    end
    
    def authenticate_spotify
        if current_user.user_hash.empty?()
            redirect_to '/auth/spotify'
        end
    end
end

app/controllers/authentication_controller.rb
class AuthenticationController < ApplicationController
    before_action :authenticate_user!
    protect_from_forgery prepend: true
    before_action :authenticate_spotify
    
    def spotify
        if request.env['omniauth.auth'] 
            @spotify_user = RSpotify::User.new(request.env['omniauth.auth'])
            current_user.user_hash = @spotify_user.to_hash
            current_user.save
        else
            redirect_to '/auth/spotify'
        end
    end 
end

app/controllers/playlists_controller.rb
class PlaylistsController < ApplicationController
    before_action :authenticate_user!
    before_action :authenticate_spotify
    
    # GET /playlists
    def index
        @playlists = Playlist.all()
    end

    # GET /playlists/{id}
    def show 
        @playlist = Playlist.find(params[:id])
        RemoveTrackJob.set(wait: 210.seconds).perform_later(@playlist.user.id,@playlist.id)

        @playlist
    end

    # GET /playlists/new
    def new 
        @playlist = Playlist.new
    end

    # POST /playlists
    def create
        @service = PlaylistServices::Create.call(current_user,playlist_params)

        render_service
    end

    # GET /playlists/{id}/edit
    def edit 
        @playlist = Playlist.find(params[:id])
    end 

    # PUT /playlists/{id}
    def update
        @service = PlaylistServices::Update.call(params[:id],playlist_params)

        render_service
    end

    #DELETE /playlists/{id}
    def destroy
        @playlist = Playlist.find(params[:id])
        spotify_playlist = RSpotify::Playlist.find_by_id(@playlist.id_spotify)

        spotify_playlist.remove_tracks!(spotify_playlist.tracks)

        if @playlist.destroy
            redirect_to playlists_path
        end
    end

    private
    
    def render_service
        if @service.success?
            RemoveTrackJob.set(wait: 210.seconds).perform_later(@playlist.user.id,@playlist.id)
            redirect_to playlists_path
        else
            redirect_to '/auth/spotify'
        end
    end

    def playlist_params
        params.require(:playlist).permit(:name)
    end
end

app/controllers/tracks_controller.rb
class TracksController < ApplicationController
    include Pagy::Backend
    
    before_action :authenticate_user!
    before_action :authenticate_spotify

    #GET /tracks
    def index 
        @pagy, @tracks = pagy(Track.all())
    end

    #GET /tracks/show/{q}
    def show
        @tracks = RSpotify::Track.search(params[:q], limit: 10)
    end

    #GET /track/new?{id}
    def new
        @track = Track.new
    end

    #POST /tracks
    def create
        
        track = RSpotify::Track.find(track_params[:track_id])
        
        if Playlist.find_by(id: track_params[:playlist_id]).tracks.where(id_spotify: track.id).exists?
            return redirect_to tracks_path
        else
            AddTrackJob.perform_now(current_user,track_params[:track_id],track_params[:playlist_id])
        end

        @service = TrackServices::Create.call(track,track_params[:playlist_id])

        redirect_to tracks_path if @service.success?

    end
    
    # DELETE /tracks/{id}
    def destroy
        @track = Track.find(params[:id])
        spotify_track = RSpotify::Track.find(@track.id_spotify)
        spotify_playlist = RSpotify::Playlist.find_by_id(@track.playlist.id_spotify)

        if @track.status == "on_queue"
            spotify_playlist.remove_tracks!([spotify_track])
        end

        @track.destroy
        redirect_to tracks_path

    end 

    private 

    def track_params
        params.require(:track).permit(:track_id, :playlist_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
    include Pagy::Frontend
end

app/helpers/authentication_helper.rb
module AuthenticationHelper
end

app/helpers/playlists_helper.rb
module PlaylistsHelper
end

app/helpers/tracks_helper.rb
module TracksHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/authentication/spotify.html.erb
<h1>Bem-vindo <%= @spotify_user.display_name %> </h1>

<ul>
    <li><%= link_to 'Playlists', playlists_path %></li>

    <li><%= link_to 'Sair', destroy_user_session_path, :method => :delete %> </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>ProjetoSpotify</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/playlists/_form.html.erb
<%= form_with(model: @playlist) do |form| %>
    <div >
        <%= form.label :name %>
        <%= form.text_field :name %>
    </div>
    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/playlists/edit.html.erb
<h1> Edit Playlist </h1>
<%= render "form", playlist: @playlist %>

app/views/playlists/index.html.erb
<%= form_tag("/tracks/show", method: "get") do %>
  <%= label_tag(:q, "Search Tracks:") %>
  <%= text_field_tag(:q) %>
  <%= submit_tag("Search") %>
<% end %>
<%= link_to "Tracks", tracks_path %>
<h1> Suas Playlists </h1>
<ul>
  <% @playlists.each do |playlist| %>
    <li>
        <h4><%= playlist.name %></h4>
        <%= link_to "Usar Playlist", playlist_path(playlist) %>
        <td><%= button_to "Deletar", playlist, :method => :delete %></td>
    </li>
  <% end %>
</ul>

<%= link_to "New Playlist", new_playlist_path %>
</br>
<%= link_to 'Sair', destroy_user_session_path, :method => :delete %> 

app/views/playlists/new.html.erb
<h1>New playlist </h1>

<%= render "form", playlist: @playlist %>

app/views/playlists/show.html.erb
<h1> Usando: <%= @playlist.name %> </h1>

<ul>
    <li><%= link_to "Edit", edit_playlist_path(@playlist) %></li>
    <li><%= link_to "Voltar", playlists_path %></li>
</ul>

app/views/tracks/_form.html.erb
<%= form_with(model: track) do |form| %>
    <div class='field'>
        <%= form.label :playlist_id %>
        <%= form.collection_select :playlist_id, Playlist.all, :id, :name, include_blank: false %>
    </div>

    <%= form.text_field :track_id, value: params[:id_track] , class: "d-none" %>

    <div>
        <%= form.submit %>
    </div>
<% end %>

app/views/tracks/index.html.erb
<%= form_tag("/tracks/show", method: "get") do %>
    <%= label_tag(:q, "Search for:") %>
    <%= text_field_tag(:q) %>
    <%= submit_tag("Search") %>
 <% end %>
 <%= link_to "Playlists", playlists_path %>
 <div >
  <h1> Musicas já adiciondas </h1>

  <table class="table">
    <thead class="thead-dark">
      <tr>
        <th scope="col">ID</th>
        <th scope="col">Nome da musica</th>
        <th scope="col">PLaylist Associada</th>
        <th scope="col">Status </th>
        <th scope="col">Ação</th>
      </tr>
    </thead>
    <tbody>
      <% @tracks.each do |track| %>
        <tr>
          <th scope="row"><%= track.id %></th>
          <td><%= track.name %></td>
          <td><%= track.playlist.name %></td>
          <% if track.status == "on_queue" %>
          <td> na fila </td>
          <% else %> 
          <td> já tocada </td>
          <% end %>
          <td><%= button_to "Deletar", track, :method => :delete %></td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <%== pagy_nav(@pagy) %>
</div>

app/views/tracks/new.html.erb
<%= render 'form' , track: @track%>

app/views/tracks/show.html.erb
<% @tracks.each do |track| %>
    <p> <%= track.name %> </p>
    <p> <%= track.artists[0].name %> </p>
    <%= link_to "Adicionar Musica a Playlist", new_track_path(id_track: track.id)  %>
<% end %>